apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-frontend-xzjo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-frontend-xzjo
    app.kubernetes.io/part-of: my-app
  name: pacman-frontend-xzjo
  namespace: user1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: pacman-frontend-xzjo
status:
  loadBalancer: {}
